# Generated by Django 4.2.5 on 2023-09-18 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 19, 20, 37, 30129, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 19, 20, 37, 30129, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 19, 20, 37, 30129, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 18, 19, 20, 37, 30129, tzinfo=datetime.timezone.utc), verbose_name='Время'),
        ),
    ]
