# Generated by Django 4.2.5 on 2023-09-18 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='facults', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.CharField(choices=[('Enabled', 'Действует'), ('Deleted', 'Удалена')], default='Enabled', max_length=100, verbose_name='Статус')),
                ('course', models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (5, 'Пятый'), (6, 'Шестой')], default=1, verbose_name='Курс')),
                ('education_type', models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Специалитет', 'Специалитет'), ('Магистратура', 'Магистратура'), ('Аспирантура', 'Аспирантура')], default='Бакалавриат', verbose_name='Вариант обучения')),
                ('year_begin', models.IntegerField(default=2023, verbose_name='Год начала обучения')),
                ('year_end', models.IntegerField(default=2027, verbose_name='Год конца обучения')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name='Имя')),
                ('middle_name', models.CharField(verbose_name='Фамилия')),
                ('last_name', models.CharField(verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(default='', verbose_name='Дисциплина')),
                ('time', models.TimeField(default=datetime.datetime(2023, 9, 18, 14, 9, 18, 688180, tzinfo=datetime.timezone.utc), verbose_name='Время')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], default=1, verbose_name='День недели')),
                ('term', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='Семестр')),
                ('status', models.CharField(choices=[('Injected', 'Введён'), ('At work', 'В работе'), ('Сompleted', 'Завершён'), ('Cancelled', 'Отменён'), ('Deleted', 'Удалён')], default='Введён', max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 18, 14, 9, 18, 688180, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 9, 18, 14, 9, 18, 688180, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 9, 18, 14, 9, 18, 688180, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('groups', models.ManyToManyField(to='schedule.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
