# Generated by Django 4.2.4 on 2023-10-08 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='facults', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название группы', max_length=100, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, max_length=100, verbose_name='Статус')),
                ('course', models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (5, 'Пятый'), (6, 'Шестой')], default=1, verbose_name='Курс')),
                ('education_type', models.IntegerField(choices=[(1, 'Бакалавриат'), (2, 'Специалитет'), (3, 'Магистратура'), (4, 'Аспирантура')], default=1, verbose_name='Вариант обучения')),
                ('year_begin', models.IntegerField(default=2023, verbose_name='Год начала обучения')),
                ('year_end', models.IntegerField(default=2027, verbose_name='Год конца обучения')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(default='Дисциплина', verbose_name='Дисциплина')),
                ('audience', models.CharField(default='Аудитория', verbose_name='Аудитория')),
                ('teacher', models.CharField(default='Преподаватель', verbose_name='Преподаватель')),
                ('time', models.IntegerField(choices=[(1, '8:30'), (2, '10:15'), (3, '12:00'), (4, '13:50'), (5, '15:40'), (6, '17:25'), (7, '19:10')], default=1, verbose_name='Время начала')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=7, verbose_name='День недели')),
                ('term', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='Семестр')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 10, 8, 13, 38, 52, 933757, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(default=datetime.datetime(2023, 10, 8, 13, 38, 52, 933757, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(default=datetime.datetime(2023, 10, 8, 13, 38, 52, 933757, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения')),
                ('groups', models.ManyToManyField(to='schedule.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ('id',),
            },
        ),
    ]
