# Generated by Django 4.2.5 on 2023-10-16 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 8, 14, 3, 351739, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 8, 14, 3, 351739, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 8, 14, 3, 351739, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], default=1, verbose_name='День недели'),
        ),
    ]
